os:
  - osx
  - linux

language: swift

install: swift package update

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04
    - os: osx
      osx_image: xcode9.2
      sudo: required

script:
  - swift test